version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: project_management_app-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    container_name: project_management_app-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - database